name: Daily Study Check

on:
  schedule:
    - cron: '20 4 * * *'  # Runs at 00:04:20 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-studies:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add explicit permission to write to repo
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Important for accessing git history
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run study checker
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python src/main.py
      
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add studies.db
        git diff --quiet && git diff --staged --quiet || git commit -m "Update studies database"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
