name: Daily Study Check

on:
  schedule:
    - cron: '20 4 * * *'  # Runs at 00:04:20 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-studies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Important for accessing git history
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run study checker
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python src/main.py
      
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add studies.db
        git commit -m "Update studies database" || exit 0
        git push
